### PR TITLE
Update Details.js

### PR DESCRIPTION
**Pull request by Megachip**
Suggestion for issue #73 
But maybe this would fit better into tools. 

**untested**

### CODE REVIEW

**Review by sohcah — CHANGES_REQUESTED** [review]
Probably best to use a similar mechanism to is used for the Inventory Button, where the button is disabled and the arrow is replaced by a lock icon. See line 107 for an example,

**Comment by Megachip** [comment]
> Probably best to use a similar mechanism to is used for the Inventory Button, where the button is disabled and the arrow is replaced by a lock icon. See line 107 for an example,

Isn't it, what the change did? Ah, missed changing the icon ;) 

But for my feeling it would better fit into tools ;) ... but just an opinion/feeling ;)

**Review by sohcah — APPROVED** [review]
Awesome. Thanks for the PR. I'll merge for the next update. I'll no longer be alone on the developer section of the credits. :)

**Comment by Megachip** [comment]
> Awesome. Thanks for the PR. I'll merge for the next update. I'll no longer be alone on the developer section of the credits. :)

^^ That's not developing ;) You putting pressure on me to find more time for that awesome project. But will try my best ^^

**Comment by sohcah** [comment]
> > Probably best to use a similar mechanism to is used for the Inventory Button, where the button is disabled and the arrow is replaced by a lock icon. See line 107 for an example,
> 
> 
> 
> Isn't it, what the change did? Ah, missed changing the icon ;) 
> 
> 
> 
> But for my feeling it would better fit into tools ;) ... but just an opinion/feeling ;)

It wouldn't work in tools as it depends on which user it is opened as. It has to exclude munzees that the user has captured. :)

**Comment by sohcah** [comment]
> > Awesome. Thanks for the PR. I'll merge for the next update. I'll no longer be alone on the developer section of the credits. :)
> 
> 
> 
> ^^ That's not developing ;) You putting pressure on me to find more time for that awesome project. But will try my best ^^ 

Don't worry, I'll put you as "Code Contributer". No pressure to do anything, but I feel it's nice to give people credit for what they do. 😀

**Pull request merged**
